<?php
require __DIR__.'/core.php';
try { if(!query('SELECT COUNT(*) FROM admins')->fetchColumn()) go('install.php'); } catch(Throwable $ex) { head('Conectar banco'); echo '<section class="card narrow"><h1>Vamos começar?</h1><p>Ligue o Apache e o MySQL no painel do XAMPP. No primeiro acesso, abra o instalador.</p><a class="button" href="install.php">Preparar sistema</a><p>Se já instalou, confira a conexão em config.php.</p></section>'; foot(); exit; }
$page=$_GET['page']??'booking'; $error='';
if($page==='slots') { header('Content-Type: application/json; charset=utf-8'); echo json_encode(slots((string)($_GET['date']??''),(int)($_GET['service']??0))); exit; }
$adminPages=['admin','services','settings','blocks','patients']; if(in_array($page,$adminPages,true)) auth();
$manage=null; if($page==='manage') { $manage=query('SELECT a.*,s.name AS service_name FROM appointments a JOIN services s ON s.id=a.service_id WHERE manage_token=?',[(string)($_GET['token']??'')])->fetch(); if(!$manage) { http_response_code(404); head('Reserva não encontrada'); echo '<section class="card"><h1>Link inválido.</h1><p>Confira o link recebido ao agendar.</p></section>'; foot(); exit; } header('Referrer-Policy: no-referrer'); }
if($_SERVER['REQUEST_METHOD']==='POST') { try { checkCsrf(); $action=$_POST['action']??'';
 if($action==='login') {
  $ip=$_SERVER['REMOTE_ADDR']??'local'; $attempt=query('SELECT * FROM login_attempts WHERE ip=?',[$ip])->fetch();
  if($attempt && $attempt['attempts']>=5 && strtotime($attempt['updated_at'])>time()-900) throw new RuntimeException('Muitas tentativas. Aguarde 15 minutos.');
  $user=query('SELECT * FROM admins WHERE email=?',[trim($_POST['email']??'')])->fetch();
  if(!$user || !password_verify($_POST['password']??'',$user['password'])) { query('INSERT INTO login_attempts(ip,attempts,updated_at) VALUES(?,1,NOW()) ON DUPLICATE KEY UPDATE attempts=IF(updated_at<DATE_SUB(NOW(), INTERVAL 15 MINUTE),1,attempts+1),updated_at=NOW()',[$ip]); throw new RuntimeException('E-mail ou senha incorretos.'); }
  query('DELETE FROM login_attempts WHERE ip=?',[$ip]); session_regenerate_id(true); $_SESSION['admin']=$user['id']; go('index.php?page=admin');
 }
 elseif($action==='logout') { $_SESSION=[]; session_destroy(); go('index.php'); }
 elseif($action==='book') { if(empty($_POST['consent'])) throw new RuntimeException('Confirme o uso dos dados para realizar o agendamento.'); $id=book($_POST); $key=query('SELECT manage_token FROM appointments WHERE id=?',[$id])->fetchColumn(); go('index.php?page=manage&token='.$key.'&saved=1'); }
 elseif(in_array($action,['cancel','reschedule'],true)) {
  if(!$manage) throw new RuntimeException('Link inválido.');
  locked(function() use($manage,$action) { $current=query('SELECT * FROM appointments WHERE id=?',[$manage['id']])->fetch(); if(!in_array($current['status'],['aguardando','confirmado'],true)||strtotime($current['starts'])<=time()) throw new RuntimeException('Esse atendimento não pode mais ser alterado pelo link. Entre em contato com a clínica.');
   if($action==='cancel') query("UPDATE appointments SET status='cancelado' WHERE id=?",[$manage['id']]);
   else book(array_merge($_POST,['name'=>$current['name'],'phone'=>$current['phone']]),(int)$current['id']);
  }); go('index.php?page=manage&token='.urlencode($manage['manage_token']).'&saved=1');
 }
 else { auth();
  if($action==='status') { $status=$_POST['status']??''; if(!in_array($status,['confirmado','cancelado','concluido','faltou'],true)) throw new RuntimeException('Status inválido.'); locked(function() use($status) { $row=query('SELECT status FROM appointments WHERE id=?',[(int)$_POST['id']])->fetchColumn(); if(!in_array($row,['aguardando','confirmado'],true)) throw new RuntimeException('Atendimento encerrado. Crie um novo agendamento se necessário.'); query('UPDATE appointments SET status=? WHERE id=?',[$status,(int)$_POST['id']]); }); }
  elseif($action==='service') { $name=trim($_POST['name']??''); $duration=(int)($_POST['duration']??0); if(mb_strlen($name)<3||mb_strlen($name)>120||$duration<15||$duration>240) throw new RuntimeException('Nome de 3 a 120 caracteres e duração entre 15 e 240 minutos.'); query('INSERT INTO services(name,duration) VALUES(?,?)',[$name,$duration]); }
  elseif($action==='toggle') query('UPDATE services SET active=1-active WHERE id=?',[(int)$_POST['id']]);
  elseif($action==='settings') { $open=$_POST['open']??''; $close=$_POST['close']??''; $days=array_values(array_intersect(['1','2','3','4','5','6','7'],$_POST['days']??[])); $gap=(int)($_POST['gap']??0); if(!preg_match('/^([01]\d|2[0-3]):[0-5]\d$/',$open)||!preg_match('/^([01]\d|2[0-3]):[0-5]\d$/',$close)||$open>=$close||!$days||$gap<0||$gap>120) throw new RuntimeException('Confira os dias, horário de abertura, fechamento e intervalo.'); locked(function() use($open,$close,$days,$gap) { db()->beginTransaction(); try { foreach(['open'=>$open,'close'=>$close,'days'=>implode(',',$days),'gap'=>(string)$gap] as $k=>$v) query('UPDATE settings SET value=? WHERE name=?',[$v,$k]); db()->commit(); } catch(Throwable $e) { db()->rollBack(); throw $e; } }); }
  elseif($action==='block') { $start=str_replace('T',' ',$_POST['starts']??''); $end=str_replace('T',' ',$_POST['ends']??''); $reason=trim($_POST['reason']??''); if(!DateTimeImmutable::createFromFormat('!Y-m-d H:i',$start)||!DateTimeImmutable::createFromFormat('!Y-m-d H:i',$end)||$start>=$end||mb_strlen($reason)>120) throw new RuntimeException('Informe início e fim válidos.'); locked(function() use($start,$end,$reason) { if(query("SELECT COUNT(*) FROM appointments WHERE status<>'cancelado' AND starts < ? AND ends > ?",[$end,$start])->fetchColumn()) throw new RuntimeException('Já existe atendimento nesse período. Reagende ou cancele antes de bloquear.'); query('INSERT INTO blocks(starts,ends,reason) VALUES(?,?,?)',[$start,$end,$reason?:'Indisponível']); }); }
  elseif($action==='unblock') locked(fn()=>query('DELETE FROM blocks WHERE id=?',[(int)$_POST['id']]));
  elseif($action==='password') { $user=query('SELECT * FROM admins WHERE id=?',[$_SESSION['admin']])->fetch(); if(!password_verify($_POST['current']??'',$user['password'])||strlen($_POST['password']??'')<10) throw new RuntimeException('Confira a senha atual. A nova senha deve ter ao menos 10 caracteres.'); query('UPDATE admins SET password=? WHERE id=?',[password_hash($_POST['password'],PASSWORD_DEFAULT),$_SESSION['admin']]); }
  else throw new RuntimeException('Ação inválida.');
  go('index.php?page='.urlencode($page).'&saved=1'.(isset($_GET['date'])?'&date='.urlencode($_GET['date']):''));
 }
 } catch(Throwable $ex) { $error=$ex instanceof PDOException?'Não foi possível salvar. Confira o banco de dados e tente novamente.':$ex->getMessage(); }
}
head('Agenda online');
if($error) echo '<p class="alert" role="alert">'.e($error).'</p>';
if(isset($_GET['saved'])) echo '<p class="success" role="status">Pronto! As informações foram salvas.</p>';
function bookingForm(?array $appointment=null): void { $services=query('SELECT * FROM services WHERE active=1 ORDER BY id')->fetchAll(); ?>
<form method="post" id="booking-form"><?=token()?><input type="hidden" name="action" value="<?=$appointment?'reschedule':'book'?>">
<label>Tipo de atendimento<select id="service" name="service" required><option value="">Selecione um serviço</option><?php foreach($services as $s): ?><option value="<?=$s['id']?>" <?=((string)($appointment['service_id']??$_POST['service']??'')===(string)$s['id'])?'selected':''?>><?=e($s['name'])?> · <?=$s['duration']?> min</option><?php endforeach ?></select></label>
<label>Data do atendimento<input id="date" type="date" name="date" min="<?=date('Y-m-d')?>" max="<?=date('Y-m-d',strtotime('+90 days'))?>" value="<?=e($_POST['date']??date('Y-m-d'))?>" required></label>
<fieldset><legend>Horários disponíveis</legend><div id="times" class="times" aria-live="polite">Escolha o serviço e a data.</div></fieldset>
<?php if(!$appointment): ?><div class="two"><label>Nome completo<input name="name" maxlength="120" minlength="3" value="<?=e($_POST['name']??'')?>" autocomplete="name" required></label><label>Celular com DDD<input type="tel" name="phone" maxlength="20" value="<?=e($_POST['phone']??'')?>" placeholder="(11) 99999-9999" autocomplete="tel" required></label></div><label class="check"><input type="checkbox" name="consent" required> Autorizo o uso do nome e telefone para organizar e entrar em contato sobre este agendamento.</label><?php endif ?>
<button id="submit-booking" disabled><?=$appointment?'Salvar novo horário':'Solicitar agendamento'?> <span>→</span></button><p class="muted">O horário será reservado e ficará aguardando confirmação da clínica.</p></form><script src="app.js" defer></script>
<?php }
if($page==='login'): ?>
<section class="card narrow"><span class="eyebrow">ACESSO RESTRITO</span><h1>Bem-vindo de volta.</h1><p>Entre para cuidar da sua agenda.</p><?php if(isset($_GET['installed'])): ?><p class="success">Instalação concluída! Use o acesso que você criou.</p><?php endif ?><form method="post"><?=token()?><input type="hidden" name="action" value="login"><label>E-mail<input type="email" name="email" autocomplete="username" required></label><label>Senha<input type="password" name="password" autocomplete="current-password" required></label><button>Entrar</button></form></section>
<?php elseif($page==='manage'): ?>
<section class="card narrow"><span class="eyebrow">SEU ATENDIMENTO</span><h1><?=e($manage['name'])?>, sua reserva está aqui.</h1><p class="badge <?=e($manage['status'])?>"><?=e(ucfirst($manage['status']))?></p><h2><?=date('d/m/Y',strtotime($manage['starts']))?> às <?=date('H:i',strtotime($manage['starts']))?></h2><p><?=e($manage['service_name'])?></p><div class="notice"><b>Guarde este link privado.</b><p>Ele permite consultar, cancelar ou reagendar. Não compartilhe com outras pessoas.</p><input aria-label="Link privado da reserva" readonly value="<?=e('http'.(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'?'s':'').'://'.($_SERVER['HTTP_HOST']??'localhost').strtok($_SERVER['REQUEST_URI'],'?').'?page=manage&token='.$manage['manage_token'])?>"></div>
<?php if(in_array($manage['status'],['aguardando','confirmado'],true)&&strtotime($manage['starts'])>time()): ?><details><summary>Alterar data ou horário</summary><?php bookingForm($manage) ?></details><form method="post" class="confirm-action" data-confirm="Deseja cancelar este atendimento?"><?=token()?><input type="hidden" name="action" value="cancel"><button class="danger">Cancelar agendamento</button></form><script src="confirm.js" defer></script><?php endif ?></section>
<?php elseif(in_array($page,$adminPages,true)): ?>
<div class="dashboard"><aside><span class="eyebrow">CONSULTÓRIO</span><?php foreach(['admin'=>'Agenda','patients'=>'Pacientes','services'=>'Serviços','blocks'=>'Bloqueios','settings'=>'Configurações'] as $key=>$label): ?><a class="<?=$page===$key?'active':''?>" href="index.php?page=<?=$key?>"><?=$label?></a><?php endforeach ?><form method="post"><?=token()?><input type="hidden" name="action" value="logout"><button class="secondary">Sair da conta</button></form></aside><section>
<?php if($page==='admin'): $date=validDate($_GET['date']??'')?$_GET['date']:date('Y-m-d'); $appointments=query('SELECT a.*,s.name AS service_name FROM appointments a JOIN services s ON a.service_id=s.id WHERE DATE(a.starts)=? ORDER BY a.starts',[$date])->fetchAll(); $active=array_filter($appointments,fn($a)=>$a['status']!=='cancelado'); ?>
<div class="section-title"><div><span class="eyebrow">VISÃO DO DIA</span><h1>Sua agenda</h1></div><a class="button" href="index.php">+ Novo agendamento</a></div><div class="stats"><div class="card"><strong><?=count($active)?></strong>atendimentos</div><div class="card"><strong><?=count(array_filter($active,fn($a)=>$a['status']==='confirmado'))?></strong>confirmados</div><div class="card"><strong><?=count(array_filter($active,fn($a)=>$a['status']==='aguardando'))?></strong>aguardando</div></div><form class="inline date-filter" method="get"><input type="hidden" name="page" value="admin"><label>Escolher dia<input type="date" name="date" value="<?=e($date)?>" required></label><button>Ver agenda</button></form>
<div class="card"><?php if(!$appointments): ?><div class="empty"><h2>Seu dia está livre.</h2><p>Nenhum agendamento para esta data.</p></div><?php endif ?><?php foreach($appointments as $a): ?><article class="appointment"><div class="hour"><?=date('H:i',strtotime($a['starts']))?><small><?=date('H:i',strtotime($a['ends']))?></small></div><div class="patient"><h3><?=e($a['name'])?></h3><p><?=e($a['service_name'])?> · <?=e($a['phone'])?></p><a href="index.php?page=manage&token=<?=e($a['manage_token'])?>">Detalhes / reagendar</a></div><div><span class="badge <?=e($a['status'])?>"><?=e(ucfirst($a['status']))?></span><?php if(in_array($a['status'],['aguardando','confirmado'],true)): ?><form method="post" class="inline status-form"><?=token()?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?=$a['id']?>"><select aria-label="Novo status" name="status"><option value="confirmado">Confirmar</option><option value="concluido">Concluído</option><option value="faltou">Faltou</option><option value="cancelado">Cancelar</option></select><button>Salvar</button></form><?php endif ?></div></article><?php endforeach ?></div>
<?php elseif($page==='services'): ?><h1>Serviços</h1><p>Desative um serviço para retirá-lo das novas reservas. Os atendimentos existentes são preservados.</p><div class="card"><?php foreach(query('SELECT * FROM services ORDER BY id') as $s): ?><div class="list-row"><div><b><?=e($s['name'])?></b><p><?=$s['duration']?> minutos · <?=$s['active']?'Ativo':'Inativo'?></p></div><form method="post"><?=token()?><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$s['id']?>"><button class="secondary"><?=$s['active']?'Desativar':'Ativar'?></button></form></div><?php endforeach ?></div><div class="card"><h2>Novo serviço</h2><form method="post"><?=token()?><input type="hidden" name="action" value="service"><label>Nome<input name="name" maxlength="120" required></label><label>Duração em minutos<input name="duration" type="number" min="15" max="240" value="60" required></label><button>Adicionar serviço</button></form></div>
<?php elseif($page==='patients'): ?><h1>Pacientes</h1><p>Contatos reunidos a partir dos agendamentos.</p><form method="get" class="inline"><input type="hidden" name="page" value="patients"><input aria-label="Buscar paciente" name="q" placeholder="Buscar nome ou telefone" value="<?=e($_GET['q']??'')?>"><button>Buscar</button></form><div class="card"><?php $q='%'.($_GET['q']??'').'%'; $patients=query('SELECT name,phone,COUNT(*) AS total,MAX(starts) AS last_visit FROM appointments WHERE name LIKE ? OR phone LIKE ? GROUP BY name,phone ORDER BY name LIMIT 200',[$q,$q])->fetchAll(); if(!$patients) echo '<p>Nenhum paciente encontrado.</p>'; foreach($patients as $p): ?><div class="list-row"><div><b><?=e($p['name'])?></b><p><?=e($p['phone'])?></p></div><span><?=$p['total']?> reservas<br><small>Última data: <?=date('d/m/Y',strtotime($p['last_visit']))?></small></span></div><?php endforeach ?></div>
<?php elseif($page==='blocks'): ?><h1>Bloqueios de agenda</h1><p>Reserve pausas, almoço, férias ou períodos sem atendimento.</p><div class="card"><form method="post"><?=token()?><input type="hidden" name="action" value="block"><div class="two"><label>Início<input type="datetime-local" name="starts" required></label><label>Fim<input type="datetime-local" name="ends" required></label></div><label>Motivo (visível só no painel)<input name="reason" maxlength="120" placeholder="Ex.: Almoço"></label><button>Bloquear período</button></form></div><div class="card"><?php $blocks=query('SELECT * FROM blocks WHERE ends>NOW() ORDER BY starts')->fetchAll(); if(!$blocks) echo '<p>Nenhum bloqueio futuro.</p>'; foreach($blocks as $b): ?><div class="list-row"><div><b><?=e($b['reason'])?></b><p><?=date('d/m/Y H:i',strtotime($b['starts']))?> até <?=date('d/m/Y H:i',strtotime($b['ends']))?></p></div><form method="post"><?=token()?><input type="hidden" name="action" value="unblock"><input type="hidden" name="id" value="<?=$b['id']?>"><button class="secondary">Liberar</button></form></div><?php endforeach ?></div>
<?php elseif($page==='settings'): ?><h1>Configurações</h1><div class="card"><h2>Disponibilidade</h2><p>Novos horários começam a cada 30 minutos, dentro do expediente. Alterações não movem reservas existentes.</p><form method="post"><?=token()?><input type="hidden" name="action" value="settings"><div class="two"><label>Abertura<input type="time" name="open" value="<?=e(setting('open'))?>" required></label><label>Fechamento<input type="time" name="close" value="<?=e(setting('close'))?>" required></label></div><fieldset><legend>Dias de atendimento</legend><div class="days"><?php foreach(['1'=>'Seg','2'=>'Ter','3'=>'Qua','4'=>'Qui','5'=>'Sex','6'=>'Sáb','7'=>'Dom'] as $v=>$label): ?><label class="check"><input type="checkbox" name="days[]" value="<?=$v?>" <?=in_array((string)$v,explode(',',setting('days')),true)?'checked':''?>><?=$label?></label><?php endforeach ?></div></fieldset><label>Intervalo entre atendimentos (minutos)<input type="number" name="gap" min="0" max="120" value="<?=e(setting('gap'))?>" required></label><button>Salvar disponibilidade</button></form></div><div class="card"><h2>Alterar senha</h2><form method="post"><?=token()?><input type="hidden" name="action" value="password"><label>Senha atual<input type="password" name="current" autocomplete="current-password" required></label><label>Nova senha<input type="password" name="password" minlength="10" autocomplete="new-password" required></label><button>Atualizar senha</button></form></div>
<?php endif ?></section></div><script src="confirm.js" defer></script>
<?php else: ?><div class="booking-layout"><section class="intro"><span class="eyebrow">CUIDADO QUE COMEÇA COM FACILIDADE</span><h1>Seu próximo passo<br>para se sentir <em>melhor.</em></h1><p>Escolha o atendimento e encontre um horário que combine com a sua rotina.</p><div class="features"><p><b>01</b> Escolha o serviço</p><p><b>02</b> Encontre seu horário</p><p><b>03</b> Informe seus dados</p></div><div class="notice">Já tem um agendamento?<br>Use o link privado gerado ao fazer sua reserva.</div></section><section class="card booking-card"><span class="eyebrow">AGENDE SEU ATENDIMENTO</span><h2>Vamos encontrar um horário?</h2><p>Reserve em poucos passos.</p><?php bookingForm() ?></section></div><?php endif; foot(); ?>
